--- 
abstract: Console application for running Perl 5 Installer (P5I) files
author: Adam Kennedy <adamk@cpan.org>
build_requires: 
  LWP::Online: 0.02
  Test::More: 0.42
  Test::Script: 1.02
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: pip
no_index: 
  directory: 
    - inc
    - t
requires: 
  Archive::Tar: 0
  CPAN: 1.76
  CPAN::Inject: 0.07
  Carp: 0
  File::Basename: 0
  File::Spec: 0.80
  File::Temp: 0.15
  File::Which: 0.05
  File::pushd: 0.32
  Getopt::Long: 0
  IO::Zlib: 0
  LWP::Simple: 0
  Params::Util: 0.21s
  URI: 0
  perl: 5.005
version: 0.10
